title: "[주간업무동향] O월 O주차"
labels: ["주간보고"]
body:
  - type: markdown
    attributes:
      value: |
        > 한 주, 고생한 팀원들을 위해 👏👏
  - type: textarea
    id: greetings
    attributes:
      value: |
        한 주, 고생 많으셨어요 👏
        이렇게 또, 여러분과 함께해서 기쁘고 행복하네요.  
        차분히 이번주를 되돌아보고, 밝은 다음주를 생각해 봐요. 😍
